# Workflow for testing branch 'devel'
# - build tests
# - various runtime tests

name: Devel build and tests
run-name: Devel build and tests
on:
  push:
    branches:
      - devel
jobs:
  build-simple:
    name: Simple build tests
    strategy:
      matrix:
        compiler: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo modprobe btrfs
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev python3-sphinx sphinx-rtd-theme-common
      - name: Configure
        run: ./autogen.sh && CC=${{ matrix.compiler}} ./configure
      - name: Documentation
        run: make V=1 -C Documentation
      - name: Make static
        run: make V=1 EXTRA_CFLAGS='-march=x86-64' static
      - name: Make box.static
        run: make V=1 EXTRA_CFLAGS='-march=x86-64' btrfs.box.static
  build-musl:
    name: Build test on musl
    runs-on: ubuntu-latest
    steps:
      - name: Musl build
        run: sudo docker run kdave/ci-musl-x86_64 ./test-build $GITHUB_REF_NAME --disable-documentation --disable-backtrace --disable-libudev
  test-quick:
    name: Quick tests
    strategy:
      matrix:
        compiler: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo modprobe btrfs
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev libaio-dev liburing-dev attr jq
      - name: Configure
        run: ./autogen.sh && CC=${{ matrix.compiler }} ./configure --disable-documentation
      - name: Make
        run: make V=1
      - name: Test internal APIs
        run: make test-api
      - name: Libbtrfsutil test
        run: make test-libbtrfsutil
      - name: Libbtrfs build test
        run: make library-test
      - name: Libbtrfs build test (static)
        run: make library-test.static
      - name: Tests ioctl
        run: make ioctl-test
      - name: Tests hash (speed)
        run: make hash-speedtest && ./hash-speedtest 1
      - name: Tests hash (correctness)
        run: make hash-vectest && ./hash-vectest
  test-mkfs:
    name: Test mkfs.btrfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo modprobe btrfs
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev libaio-dev liburing-dev attr jq
      - name: Configure
        run: ./autogen.sh && ./configure --disable-documentation
      - name: Make
        run: make V=1
      - name: Tests mkfs
        run: sudo make TEST_LOG=dump test-mkfs
  test-check:
    name: Test btrfs check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo modprobe btrfs
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev libaio-dev liburing-dev attr jq
      - name: Configure
        run: ./autogen.sh && ./configure --disable-documentation
      - name: Make
        run: make V=1
      - name: Tests check
        run: sudo make TEST_LOG=dump test-check
      - name: Tests check (lowmem)
        run: sudo make TEST_LOG=dump test-check-lowmem
  test-misc:
    name: Test misc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo modprobe btrfs
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev libaio-dev liburing-dev attr jq
      - name: Configure
        run: ./autogen.sh && ./configure --disable-documentation
      - name: Make
        run: make V=1
      - name: Tests misc
        run: sudo make TEST_LOG=dump test-misc
  test-other:
    name: Test cli, fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo modprobe btrfs
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev libaio-dev liburing-dev attr jq
      - name: Configure
        run: ./autogen.sh && ./configure --disable-documentation
      - name: Make
        run: make V=1
      - name: Tests cli
        run: sudo make TEST_LOG=dump test-cli
      - name: Tests fuzz
        run: sudo make TEST_LOG=dump test-fuzz
